services:
  nginx:
    container_name: acc-nginx
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /home/ubuntu/AtomicChargeCalculator/src/deployment/nginx/${NGINX_CONFIG_FILE:-nginx.prod.conf}:/etc/nginx/nginx.conf
      - /home/ubuntu/AtomicChargeCalculator/src/deployment/nginx/snippets:/etc/nginx/snippets
    networks:
      - acc-network
    restart: 
      unless-stopped
  db:
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres_prod
      POSTGRES_USER: prod_user
      POSTGRES_PASSWORD: ${DB_PASSWORD}
  api:
    ports:
      - "8000:8000"
    environment:
      ACC_DB_URL: "postgresql://prod_user:${DB_PASSWORD}@db:5432/postgres_prod"
      OIDC_CLIENT_ID: ${OIDC_CLIENT_ID}
      OIDC_CLIENT_SECRET: ${OIDC_CLIENT_SECRET}
      OIDC_BASE_URL: ${OIDC_BASE_URL}
      OIDC_REDIRECT_URL: ${OIDC_REDIRECT_URL}
    volumes:
      - /home/acc:/home/acc
      - /var/log/acc:/var/log/acc
  web:
    build:
      args:
        VITE_BASE_API_URL: ${VITE_BASE_API_URL}
    ports:
      - "3000:3000"
