services:
  nginx:
    container_name: acc-nginx
    image: nginx
    volumes:
      - ./nginx/nginx-dev.conf:/etc/nginx/nginx.conf:Z
      - ./nginx/snippets:/etc/nginx/snippets:Z
    networks:
      - acc-network
    restart: 
      unless-stopped
    depends_on:
      - api

  db:
    container_name: acc-db
    image: postgres:17-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${POSTGRES_USER:-postgres}" ]
      interval: 1s
      timeout: 10s
      retries: 5
    networks:
      - acc-network
    restart: unless-stopped

  api:
    container_name: acc-api
    build: 
      context: ../backend
      dockerfile: Dockerfile
    environment:
      ACC2_DB_URL: "postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@db:5432/${POSTGRES_DB:-postgres}"
      CHARGEFW2_INSTALL_DIR: ${CHARGEFW2_INSTALL_DIR:-/ChargeFW2/}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - acc-network
    restart: unless-stopped

  web:
    container_name: acc-web
    build: 
      context: ../frontend
      args:
        - VITE_BASE_API_URL
    networks:
      - acc-network
    restart: unless-stopped

networks:
  acc-network:


volumes:
  db-data:
